language: java
jdk:
  - openjdk8
jobs:
  include:
    - stage: build
      script: ./gradlew clean build

addons:
  artifacts:
    paths:
      - $TRAVIS_BUILD_DIR/build/libs
    target_paths:
      - /${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/