language: java
jdk:
  - openjdk8
jobs:
  include:
    - stage: build
      script: ./gradlew clean build

addons:
  artifacts:
    target_paths:
      - /${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/build/libs